### ISSUE TITLE
Planning 3

### ISSUE THREAD

**Issue by cyphunk** [nocompanyco/monsteranalyzer#31]
A list of milestones and todos we can try to work on

### Milestones and features

Feature changes:
- [ ] Feature: Host "active blocking" from network feature (able to choose a host and kick it from network)
  - [x] UI design
     - [x] How user turns on/off active blocking for host
     - [ ] How user sees active blocking status is on or off for host in host list
  - [ ] Code  
    - [x] @cyphunk make example code 
    - [ ] test blocking works on Karmel's side
    - [ ] run blocking code in loop to keep host offline
    - [x] allow stopping blocking loop with button
    - [x] check is it easy or hard to block two or more hosts at the same time 
    - [ ]  Check the setting page and fix it, fix the background of setting Page.
    - [ ]  clear the hostdevices and selections from redux when the user back to the main page
    - [ ] make sure the program is responsive 
    - [ ] run the program as a root
    - [x] fix the pacp issue when we run the software without the electron build
- [x] Change to Redux
- [ ] Documentation [#34]
- [ ] root permissions request to user through https://www.npmjs.com/package/sudo-prompt

### Small UI changes:

Landing Page:
- [x] When going back to LandingPage from LanPage the previouslly selected network settings should be selected (currently reverting to no selection)
- [x] Fix custom settings:
  - [x] Filter field changed to "Your IP address" (e.g. 192.168.1.22)
  - [x] Network interface  (e.g. "wlan0")
  - [x] Gateway (not used now but will be used with blocking feature eventually)
- [x] audio on intro page feels uncommon for apps, perhaps consider if we remove it
Lan Page:
- [x] Alignment of lan items should be strait or left align (see [example](https://user-images.githubusercontent.com/119662/106284970-2ac84c00-6244-11eb-8c26-e1f89aaaa04a.png))
- [x] the size of the button top bar and the buttons could be possibly much smaller (maybe 1/3 the current size?)?
- [x] the button top bar should stay on top even when scrolling lan page host list (and also stay on top when scrolling happens in other pages as well)

Info Page:
- [x] Change test values to the actual values (can ignore for the time being: filter)

About Page:
- [x] spacing between rows/items can be much smaller. Idealy user should not need to scroll to see all data.
- [x] font for title (Monster Analyzer) can be in the same font style as the rest of the application
- [x] The application icon could be smaller?

### Future?
- [ ] Feature: Network log for host
  - [ ] UI design
     - [x] Can click on host form Lan Page to see a detailed host page
     - [x] Host page shows:
       - [x] IP address, 
       - [x] Mac address, 
       - [ ] "active blocking" feature status, option to start or stop "active blocking
       - [ ] checkbox'es to select type of network traffic to show: http, https, dns, mail, other
       - [ ] A list of packet information
  - [ ]  Code
    - [ ] @cyphunk make example package data object and code 
- [ ] Figure out why there are no host names
   - [ ] `arp -a` is what local-devices uses. Can we get the names through some other way? (node npm package to find host names?)
   - [ ] @karmelyoei test Debookee LanScan to see if gets the names from your network
   - [ ] @cyphunk check if mdns provides better name resolution. Make some simple tests we can do on Karmels network
